export const GrpcError = {
	OK: 0 as const,
	CANCELLED: 1 as const,
	UNKNOWN: 2 as const,
	INVALID_ARGUMENT: 3 as const,
	DEADLINE_EXCEEDED: 4 as const,
	NOT_FOUND: 5 as const,
	ALREADY_EXISTS: 6 as const,
	PERMISSION_DENIED: 7 as const,
	UNAUTHENTICATED: 16 as const,
	RESOURCE_EXHAUSTED: 8 as const,
	FAILED_PRECONDITION: 9 as const,
	ABORTED: 10 as const,
	OUT_OF_RANGE: 11 as const,
	UNIMPLEMENTED: 12 as const,
	INTERNAL: 13 as const,
	UNAVAILABLE: 14 as const,
	DATA_LOSS: 15 as const,
}
