version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "alpha"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: alpha
