name: "Code Scanning"

on:
  push:
    branches: [main, alpha]
  pull_request:
    branches: [main, alpha]
    paths-ignore:
      - "**/*.md"

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: "typescript, javascript"
          config: |
            paths-ignore:
              - '**/__tests__'
              - '**/test'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
